add system specific setup to post-up hook and set vim noline

diff --git a/hooks/post-up b/hooks/post-up
--- a/hooks/post-up
+++ b/hooks/post-up
@@ -1,29 +1,75 @@
 #!/usr/bin/env sh
 
-fix_permissions() {
-  local arg
+# {{{ Configuration
+LOGFILE="post-up.log"
+# }}}
 
-  for arg; do
-    if [ -d "$arg" ]; then
-      chmod 700 "$arg"
-    elif [ -f "$arg" ]; then
-      chmod 600 "$arg"
-    fi
-  done
+# {{{ Utilities
+logger() { echo "$(date +'[ %d %b %Y %H %M ]') :: $*" | tee -a $log; }
+# }}}
+
+fix_permissions() {
+    local arg
+
+    for arg; do
+        logger "Fixing permissions for $arg"
+        if [ -d "$arg" ]; then
+            chmod 700 "$arg"
+        elif [ -f "$arg" ]; then
+            chmod 600 "$arg"
+        fi
+    done
 }
 
 configure_vim() {
-  local vim_dir="$HOME/.vim"
-  local plug_file="$vim_dir/autoload/plug.vim"
+    local vim_dir="$HOME/.vim"
+    local plug_file="$vim_dir/autoload/plug.vim"
 
-  mkdir -p "$vim_dir/swaps" "$vim_dir/backups"
-  if [ ! -f "$plug_file" ]; then
-    curl -fLo "$plug_file" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
-  fi
+    mkdir -p "$vim_dir/swaps" "$vim_dir/backups"
+    if [ ! -f "$plug_file" ]; then
+        curl -fLo "$plug_file" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+    fi
 
-  vim +PlugInstall! +qa
+    vim +PlugInstall! +qa
 }
 
-fix_permissions ~/.config/gnupg ~/.ssh
-configure_vim
+install_cygwin_packages() {
+    logger "Installing apt-cyg and curl"
+    lynx -source rawgit.com/transcode-open/apt-cyg/master/apt-cyg > apt-cyg &&
+    install apt-cyg /bin/ &&
+    rm apt-cyg &&
+    apt-cyg install curl
+    if [ $? -ne 0 ]; then
+        logger "Could not install curl. You will need to install it via the Cygwin Installer"
+    fi
 
+
+}
+
+apply_system_specific_setup() {
+
+    # Architecture specific actions
+    OS=$(uname -o)
+
+    case "$OS" in
+        Cygwin)
+            install_cygwin_packages
+            echo "Remember to edit /etc/passwd if you want to use zsh"
+            ;;
+        GNU/Linux)
+            ;;
+        Darwin)
+            ;;
+        *) 
+            logger "Did not recognize Operating System $OS"
+            ;;
+    esac
+}
+
+main() {
+    fix_permissions ~/.config/gnupg ~/.ssh
+    apply_system_specific_setup
+    configure_vim
+}
+
+main
