clean up bin
Signed-off-by: Max Falk <gmdfalk@gmail.com>

diff --git a/tag-bin/bin/imgur b/tag-bin/bin/imgur
--- a/tag-bin/bin/imgur
+++ b/tag-bin/bin/imgur
@@ -1,115 +1,118 @@
 #!/usr/bin/env bash
 
-# imgur script by Bart Nagel <bart@tremby.net>
-# version 4
+# Imgur script by Bart Nagel <bart@tremby.net>
+# Improvements by Tino Sino <robottinosino@gmail.com>
+# Version 6 or more
 # I release this into the public domain. Do with it what you will.
+# The latest version can be found at https://github.com/tremby/imgur.sh
 
-# Required: curl
-#
-# Optional: xsel or xclip for automatically putting the URLs on the X selection 
-# for easy pasting
-#
-# Instructions:
-# Put it somewhere in your path and maybe rename it:
-#   mv ~/Downloads/imgurbash.sh ~/bin/imgur
-# Make it executable:
-#   chmod +x ~/bin/imgur
-# Optional, since Alan kindly provided an API key for this script: stick your 
-# API key in the top:
-#   vim ~/bin/imgur
-# Upload an image:
-#   imgur images/hilarious/manfallingover.jpg
-# Upload multiple images:
-#   imgur images/delicious/cake.png images/exciting/bungeejump.jpg
-# The URLs will be displayed (and the delete page's URLs will be displayed on 
-# stderr). If you have xsel or xclip the URLs will also be put on the X 
-# selection, which you can usually paste with a middle click.
+# API Key provided by Bart;
+# replace with your own or specify yours as IMGUR_CLIENT_ID envionment variable
+# to avoid limits
+default_client_id=c9a6efb3d7932fd
+client_id="${IMGUR_CLIENT_ID:=$default_client_id}"
 
-# API Key provided by Alan@imgur.com
-apikey="b3625162d3418ac51a9ee805b1840452"
-
-# function to output usage instructions
+# Function to output usage instructions
 function usage {
-    echo "Usage: $(basename $0) <filename> [<filename> [...]]" >&2
-    echo "Upload images to imgur and output their new URLs to stdout. Each one's" >&2
-    echo "delete page is output to stderr between the view URLs." >&2
-    echo "If xsel or xclip is available, the URLs are put on the X selection for" >&2
-    echo "easy pasting." >&2
+	echo "Usage: $(basename $0) [<filename|URL> [...]]" >&2
+	echo
+	echo "Upload images to imgur and output their new URLs to stdout. Each one's" >&2
+	echo "delete page is output to stderr between the view URLs." >&2
+	echo
+	echo "A filename can be - to read from stdin. If no filename is given, stdin is read." >&2
+	echo
+	echo "If xsel, xclip, or pbcopy is available, the URLs are put on the X selection for" >&2
+	echo "easy pasting." >&2
 }
 
-# check API key has been entered
-if [ "$apikey" = "Your API key" ]; then
-    echo "You first need to edit the script and put your API key in the variable near the top." >&2
-    exit 15
+# Function to upload a path
+# First argument should be a content spec understood by curl's -F option
+function upload {
+	curl -s -H "Authorization: Client-ID $client_id" -H "Expect: " -F "image=$1" https://api.imgur.com/3/image.xml
+	# The "Expect: " header is to get around a problem when using this through
+	# the Squid proxy. Not sure if it's a Squid bug or what.
+}
+
+# Check arguments
+if [ "$1" == "-h" -o "$1" == "--help" ]; then
+	usage
+	exit 0
+elif [ $# -eq 0 ]; then
+	echo "No file specified; reading from stdin" >&2
+	exec "$0" -
 fi
 
-# check arguments
-if [ "$1" = "-h" -o "$1" = "--help" ]; then
-    usage
-    exit 0
-elif [ $# == 0 ]; then
-    echo "No file specified" >&2
-    usage
-    exit 16
-fi
-
-# check curl is available
-type curl >/dev/null 2>/dev/null || {
-    echo "Couln't find curl, which is required." >&2
-    exit 17
+# Check curl is available
+type curl &>/dev/null || {
+	echo "Couldn't find curl, which is required." >&2
+	exit 17
 }
 
 clip=""
 errors=false
 
-# loop through arguments
+# Loop through arguments
 while [ $# -gt 0 ]; do
-    file="$1"
-    shift
+	file="$1"
+	shift
 
-    # check file exists
-    if [ ! -f "$file" ]; then
-        echo "file '$file' doesn't exist, skipping" >&2
-        errors=true
-        continue
-    fi
+	# Upload the image
+	if [[ "$file" =~ ^https?:// ]]; then
+		# URL -> imgur
+		response=$(upload "$file") 2>/dev/null
+	else
+		# File -> imgur
+		# Check file exists
+		if [ "$file" != "-" -a ! -f "$file" ]; then
+			echo "File '$file' doesn't exist; skipping" >&2
+			errors=true
+			continue
+		fi
+		response=$(upload "@$file") 2>/dev/null
+	fi
 
-    # upload the image
-    response=$(curl -F "key=$apikey" -H "Expect: " -F "image=@$file" \
-        http://imgur.com/api/upload.xml 2>/dev/null)
-    # the "Expect: " header is to get around a problem when using this through 
-    # the Squid proxy. Not sure if it's a Squid bug or what.
-    if [ $? -ne 0 ]; then
-        echo "Upload failed" >&2
-        errors=true
-        continue
-    elif [ $(echo $response | grep -c "<error_msg>") -gt 0 ]; then
-        echo "Error message from imgur:" >&2
-        echo $response | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
-        errors=true
-        continue
-    fi
+	if [ $? -ne 0 ]; then
+		echo "Upload failed" >&2
+		errors=true
+		continue
+	elif echo "$response" | grep -q 'success="0"'; then
+		echo "Error message from imgur:" >&2
+		msg="${response##*<error>}"
+		echo "${msg%%</error>*}" >&2
+		errors=true
+		continue
+	fi
 
-    # parse the response and output our stuff
-    url=$(echo $response | sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/')
-    deleteurl=$(echo $response | sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/')
-    echo $url
-    echo "Delete page: $deleteurl" >&2
+	# Parse the response and output our stuff
+	url="${response##*<link>}"
+	url="${url%%</link>*}"
+	delete_hash="${response##*<deletehash>}"
+	delete_hash="${delete_hash%%</deletehash>*}"
+	echo $url | sed 's/^http:/https:/'
+	echo "Delete page: https://imgur.com/delete/$delete_hash" >&2
 
-    # append the URL to a string so we can put them all on the clipboard later
-    clip="$clip$url
-"
+	# Append the URL to a string so we can put them all on the clipboard later
+	clip+="$url"
+	if [ $# -gt 0 ]; then
+		clip+=$'\n'
+	fi
 done
 
-# put the URLs on the clipboard if we have xsel or xclip
-if [ $DISPLAY ]; then
-    { type xsel >/dev/null 2>/dev/null && echo -n $clip | xsel; } \
-        || { type xclip >/dev/null 2>/dev/null && echo -n $clip | xclip; } \
-        || echo "Haven't copied to the clipboard: no xsel or xclip" >&2
+# Put the URLs on the clipboard if we can
+if type pbcopy &>/dev/null; then
+	echo -n "$clip" | pbcopy
+elif [ $DISPLAY ]; then
+	if type xsel &>/dev/null; then
+		echo -n "$clip" | xsel -i
+	elif type xclip &>/dev/null; then
+		echo -n "$clip" | xclip
+	else
+		echo "Haven't copied to the clipboard: no xsel or xclip" >&2
+	fi
 else
-    echo "Haven't copied to the clipboard: no \$DISPLAY" >&2
+	echo "Haven't copied to the clipboard: no \$DISPLAY or pbcopy" >&2
 fi
 
 if $errors; then
-    exit 1
+	exit 1
 fi
diff --git a/tag-bin/bin/xdg-open b/tag-bin/bin/xdg-open
--- a/tag-bin/bin/xdg-open
+++ b/tag-bin/bin/xdg-open
@@ -1,4 +1,36 @@
 #!/usr/bin/env bash
+#
+# pbrisbin 2012
+#
+###
+file="$1"
 
-xdg-open "$@" &
+[[ -z "$file" ]] && { echo 'argument required' >&2; exit 1; }
 
+if [[ ! -f "$file" ]]; then
+  $BROWSER "$file" &>/dev/null &
+  exit 0
+fi
+
+if ! which xdg-mime &>/dev/null; then
+  echo 'xdg-mime required' >&2
+  exit 1
+fi
+
+read -r mimetype < \
+  <(xdg-mime query filetype "$file" 2>/dev/null | cut -d ';' -f 1)
+
+{
+  case "$mimetype" in
+    application/pdf) zathura "$file"  ;;
+    application/ogg) mplayer "$file"  ;;
+    audio/*)         mplayer "$file"  ;;
+    video/*)         mplayer "$file"  ;;
+    image/*)         mirage  "$file"  ;;
+    text/*)          urxvtc -e $EDITOR "$file" ;;
+    *)
+      echo "$file: unmatched mimetype, $mimetype" >&2
+      exit 1
+      ;;
+  esac
+} &>/dev/null
